### ISSUE TITLE
Conditionally add async tag in page editor clientlibs

### ISSUE THREAD

**Issue by rachitkumar13** [adobe/aem-spa-page-model-manager#2]
Context:
When the editor is opened inside an iframe in edit mode the corresponding clientlibs should be rendered async.

Expected Outcome:
When the PageModelManager identifies that it is loaded in the editor (isInEditor), script and style tags are being added to the DOM so that MessageChannel and placeholders can operate from within the iFrame of the Editor

**Comment by grubyak** [comment]
fixed in https://github.com/adobe/aem-spa-page-model-manager/pull/19
