### ISSUE TITLE
[bug] Node v13 dependency, blocks firebase support

### ISSUE THREAD

**Issue by drudunn** [adobe/aem-spa-page-model-manager#30]
**Describe the bug**
This library currently [requires node >=13](https://github.com/adobe/aem-spa-page-model-manager/blob/master/package.json#L20) to use. This limits our ability to use AEM alongside firebase, as [only Node 10/12 are supported](https://firebase.google.com/docs/functions/manage-functions#set_nodejs_version).

It is unclear why the specific dependency on an odd-numbered release when [Node.JS advocate](https://nodejs.org/en/about/releases/) that _"Production applications should only use Active LTS or Maintenance LTS releases"_ which are even-numbered releases.

>After six months, odd-numbered releases (9, 11, etc.) become unsupported, and even-numbered releases (10, 12, etc.) move to Active LTS status and are ready for general use.

**Package version**
1.2.x

**To Reproduce**
1. NPM Install with Node 12, (latest supported node version in firebase)
2. See standard node engine error
```
error @adobe/aem-spa-page-model-manager@1.2.1: The engine "node" is incompatible with this module. Expected version ">=13.10.1". Got "12.16.2"
```

**Expected behavior**
Expected to be able to use the current LTS versions of Node.

**Comment by grubyak** [comment]
@drudunn thanks for catching our attention on that, fixed in https://github.com/adobe/aem-spa-page-model-manager/releases/tag/v1.2.2 via https://github.com/adobe/aem-spa-page-model-manager/pull/31
