### ISSUE TITLE
[bug] Package is incompatible with IE11

### ISSUE THREAD

**Issue by angusdowling** [adobe/aem-spa-page-model-manager#34]
**Describe the bug**
This package is not compatible with IE11. This is because the TypeScript compilation target has been set to `es2018` in `tsconfig.json`. IE11 does not support the features available in es2018, and throws an error when it runs into code it cannot understand.

**Package version**
1.2.3

**Expected behavior**
The package should be compatible with IE11. A possible fix for this can be to set the compilation target to `es5` instead of `es2018`

**Screenshots**
![Error in console](https://user-images.githubusercontent.com/2599300/96538528-746bd700-12e4-11eb-8656-ceb1c363d114.png)
![Line of code throwing error](https://user-images.githubusercontent.com/2599300/96538619-a846fc80-12e4-11eb-8d8e-64a2e713b73e.png)

**Comment by pfauchere** [comment]
We do not intend to support IE11.
