### ISSUE TITLE
Editor doesn't update URLs after the active page to edit is loaded by content iframe

### ISSUE THREAD

**Issue by friendlymahi** [adobe/aem-spa-page-model-manager#44]
**Describe the bug**
When using ModelManager to load different pages as a result of a button click or link navigation, we see content is loading fine, but the Editor URL still points to the initial page. 

**Package version**
        "@adobe/aem-spa-page-model-manager": "^1.0.0",

**To Reproduce**
1. Use WKND guides project for React
2. Open a page that has navigation in it, and click one of the links
3. Navigation shall happen
4. See that there is ambiguity when comparing URL in Editor vs actual content

**Expected behavior**
URL should be updated on Editor end and all the links actions on the editor should get associated with the page being viewed in content iframe.

**Additional context**
Unsure if this issue is more on the AEM end and less on SPA editor. Please advise if this needs to be logged else where.

**Comment by pfauchere** [comment]
This issue relates to the Editor Code. We have an internal ticket to support navigation in the App from within the Editor - CQ-4300338. If the issue is critical to you please create a ticket via Customer Care.

**Comment by friendlymahi** [comment]
@pfauchere  Thanks a lot for your inputs. Will be looking forward for this issue to be fixed.
