### ISSUE TITLE
[Question] Send Query Parameters to AEM

### ISSUE THREAD

**Issue by ChazUK** [adobe/aem-spa-page-model-manager#59]
Is it possible to send the query parameters when fetching the data from AEM with the Model Manager?

https://github.com/adobe/aem-spa-page-model-manager/blob/052be877708296a386d6256c3af2c393eaff6eef/src/ModelManager.ts#L377

**Comment by niekraaijmakers** [comment]
Well. In theory anything is possible if you modify the SDK and use NPM link to put it in your project. But we never tried this.. what you could try is to modify the path outputs in the model XML but I doubt this is what you want.

If you want to send query parameters based on some client side behaviour (maybe with an eventlistener? )you will have to override the SDK and / or send some PR to make it possible.
