### ISSUE TITLE
[bug] model JSON of page is retrieved with the wrong path

### ISSUE THREAD

**Issue by niekraaijmakers** [adobe/aem-spa-page-model-manager#64]
**Describe the bug**

**Package version**
1.3.10 upwards. 1.3.9 is working.

**To Reproduce**
1: Use SPA editor 1.0 on an AEM instance 
2: Load in any page that is not included in the model root JSON so it has to be requested
3: Observe the behaviour (see screenshots)

**Expected behavior**

**Screenshots**

1.3.9:
![Screenshot 2021-06-29 at 06 36 23](https://user-images.githubusercontent.com/26429828/123738024-55c2d480-d8a4-11eb-9195-e4d87d9ec71d.png)

1.3.10+:
![Screenshot 2021-06-29 at 06 24 24](https://user-images.githubusercontent.com/26429828/123737089-a89b8c80-d8a2-11eb-8911-b8ec123b416e.png)

**Additional context**

**Comment by niekraaijmakers** [comment]
The only reason this doesn't completely break the spa editor is because the sling engine can handle this and still returns a model JSON , but still, this is quite dangerous.

**Comment by giri-jeedigunta** [comment]
Any further updates on this? same thing happens on publish URL too... if the site is `/my-app/us/en/home.html` the aem page model sends the request for `en.model.json` instead of `home.model.json`

**Comment by giri-jeedigunta** [comment]
Will try out the new version ... thank you !!!!

**Comment by giri-jeedigunta** [comment]
This is not yet fixed facing the same issue with v. 1.3.12  as well
